# Generated by Django 3.2.9 on 2021-11-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('birthDay', models.DateField()),
                ('mobileNamber', models.CharField(max_length=11)),
                ('address', models.CharField(default='address', max_length=100)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('lastName', 'firstName'),
            },
        ),
    ]
